#!/bin/sh -e
trap 'rm -rf ${PREFIX:-/tmp/misaka-test} && exit 2' 2
if=${if:-'../data/$name/$name$i.in'}
of=${of:-'../data/$name/$name$i.out'}
PREFIX=/tmp/misaka-test-`uuidgen`
mkdir $PREFIX
[ "$#" -lt 1 ] && exit 1
name=$1
TL=${2:-1}
g++ -O2 $name.cpp -o $PREFIX/$name
CUR=`pwd`
cd $PREFIX
pass=0
total=0
set +e
for ((i=1;;++i)) {
  eval [ ! -f $CUR/$if ] && break
  total=$(($total+1))
  printf "\033[01mrunning\033[0m: #$i\r"
  eval cp $CUR/$if $PREFIX/$name.in
  timeout $TL $PREFIX/$name
  if [ $? -eq 124 ] ;then
    printf "\33[2K#$i \033[33mtimeout\033[0m\n"
    continue;
  fi
  eval diff -q --ignore-all-space $CUR/$of $PREFIX/$name.out > /dev/null
  ret=$?
  if [ $ret -ne 0 ] ;then
    printf "\33[2K#$i \033[31mwrong answer\033[0m\n"
  else
    pass=$(($pass+1))
  fi
}
set -e
printf "\33[2K"
[ "$pass" -eq "$total" ] && echo -e "\033[1;32mAccepted ($total)\033[0m" || echo -e "\033[1;33mpartial: $pass/$total passed.\033[0m"
rm -rf $PREFIX

